import {database} from "./firebase-config.js";
import {ref,onValue,update,remove,runTransaction,get,onDisconnect} from "https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js";
import {criarEstadoPorJogo,normalizarEstado} from "./stateManager.js";
import {elementoCarta,nomeDe,mostrarToast,rank} from "./jogo-base.js";
import * as Truco from "./jogos/truco.js";
import * as Blackjack from "./jogos/blackjack.js";
import * as Pife from "./jogos/pife.js";

const p=new URLSearchParams(location.search),codigo=p.get("codigo"),jogadorId=sessionStorage.getItem("jogadorId");
if(!codigo||!jogadorId){location.href="index.html";throw new Error("Sala inválida");}
const salaRef=ref(database,`salas/${codigo}`),meuRef=ref(database,`salas/${codigo}/jogadores/${jogadorId}`);onDisconnect(meuRef).remove();
const $=id=>document.getElementById(id), ui={nomeJogo:$('nomeJogo'),codigo:$('codigoSala'),fase:$('faseLabel'),rodada:$('infoRodada'),aposta:$('infoAposta'),msg:$('mensagemJogo'),mesa:$('cartasMesa'),dealer:$('dealerArea'),extra:$('mesaExtra'),mao:$('minhasCartas'),help:$('handHelp'),players:$('listaParticipantes'),score:$('listaPlacar'),comprar:$('btnComprar'),passar:$('btnPassar'),desc:$('btnComprarDescarte'),truco:$('controlesTruco'),respostas:$('respostasTruco'),aceitar:$('btnAceitarTruco'),aumentar:$('btnAumentarTruco'),recusar:$('btnRecusarTruco'),nova:$('btnNovaRodada'),trocar:$('btnTrocarJogo'),organizar:$('btnOrganizar')};
ui.codigo.textContent=codigo;
let salaAtual=null,tipo=null,timerBot=null,maoCache=[];
const jogos={truco:Truco,blackjack:Blackjack,pife:Pife};
const nomes={truco:"Truco",blackjack:"Blackjack",pife:"Pife"};
function participantes(js,e){ui.players.innerHTML="";const ids=Object.entries(js).sort(([,a],[,b])=>(a.ordem||0)-(b.ordem||0));ids.forEach(([id,j])=>{const row=document.createElement('div');row.className='player-line';if(e?.atual===id&&!e.fim)row.classList.add('active');const chip=document.createElement('span');chip.className='player-chip';chip.textContent=j.tipo==='bot'?'◆':j.dono?'♛':'●';const wrap=document.createElement('div'),n=document.createElement('strong');n.textContent=id===jogadorId?`${j.nome||'Você'} · você`:j.nome||'Jogador';const s=document.createElement('small');s.textContent=j.tipo==='bot'?'BOT':j.dono?'DONO':'JOGADOR';wrap.append(n,s);row.append(chip,wrap);ui.players.append(row);});}
function placar(js,e,t){ui.score.innerHTML="";if(t==='truco'){(e.pontos||[0,0]).forEach((v,i)=>{const row=document.createElement('div');row.className='score-row';row.innerHTML=`<span>Equipe ${i===0?'A':'B'}</span><strong>${v}</strong>`;ui.score.append(row);});return;}for(const id of e.ids||[]){const row=document.createElement('div');row.className='score-row';const valor=t==='blackjack'?(e.placar?.[id]||0):(e.placar?.[id]||0);row.innerHTML=`<span>${nomeDe(js,id)}</span><strong>${valor}</strong>`;ui.score.append(row);}}
function resetActions(){[ui.comprar,ui.passar,ui.desc,ui.nova].forEach(x=>x.classList.add('escondido'));ui.truco.classList.add('escondido');ui.respostas.classList.add('escondido');ui.dealer.innerHTML="";ui.extra.innerHTML="";ui.mesa.innerHTML="";}
function showCard(c,click,hidden=false){if(hidden)return elementoCarta({valor:'🂠',naipe:''},click);return elementoCarta(c,click);}
function render(e,js){e=normalizarEstado(e);tipo=e.tipo;ui.nomeJogo.textContent=nomes[tipo]||'Jogo';ui.msg.textContent=e.resultado||'';ui.fase.textContent=tipo==='truco'?'VAZA':tipo==='blackjack'?'MÃO':'TURNO';ui.rodada.textContent=tipo==='truco'?`${e.rodada||1}/3`:tipo==='blackjack'?(e.fim?'resultado':'rodada 1'):(e.etapa==='comprar'?'comprar':'descartar');ui.aposta.textContent=tipo==='truco'?`× ${e.valor||1}`:tipo==='blackjack'?`Dealer`:`${e.descarte?.length||0} no descarte`;participantes(js,e);placar(js,e,tipo);resetActions();
 const minhaVez=e.atual===jogadorId&&!e.fim; const mao=e.maos?.[jogadorId]||[];maoCache=mao;
 ui.help.textContent=e.fim?'Confira o resultado':minhaVez?(tipo==='pife'?`Sua vez: ${e.etapa==='comprar'?'compre uma carta':'descarte uma carta'}`:'Sua vez — escolha uma ação'):'Aguardando o próximo jogador';
 if(tipo==='blackjack'){e.dealer?.forEach((c,i)=>ui.dealer.append(showCard(c,null,i===1&&!e.fim)));if(!e.fim){ui.comprar.classList.remove('escondido');ui.passar.classList.remove('escondido');ui.comprar.disabled=!minhaVez;ui.passar.disabled=!minhaVez;ui.msg.textContent=e.resultado||`Sua pontuação: ${Blackjack.pontuacao(mao)}${minhaVez?' · sua vez':''}`;}else ui.msg.textContent=e.resultado||'Rodada encerrada.';}
 if(tipo==='truco'){const vira=document.createElement('div');vira.className='eyebrow';vira.textContent=`VIRA ${e.vira?.valor||''}${e.vira?.naipe||''}`;ui.extra.append(vira);Object.values(e.jogadas||{}).forEach(c=>ui.mesa.append(elementoCarta(c)));const pedido=e.pedido?.valor;if(pedido&&e.pedido.para===jogadorId){ui.respostas.classList.remove('escondido');ui.aumentar.disabled=!Truco.proximoPedido(pedido);}else if(minhaVez&&!pedido){ui.truco.classList.remove('escondido');ui.truco.querySelectorAll('button').forEach(b=>b.disabled=Number(b.dataset.pedido)!==Truco.proximoPedido(e.valor));}}
 if(tipo==='pife'){const topo=e.descarte?.at(-1);if(topo)ui.mesa.append(elementoCarta(topo));if(minhaVez&&e.etapa==='comprar'){ui.comprar.classList.remove('escondido');ui.desc.classList.remove('escondido');ui.comprar.disabled=!e.deck?.length;ui.desc.disabled=!e.descarte?.length;} }
 ui.mao.innerHTML='';mao.forEach((c,i)=>{const pode=(tipo==='truco'&&minhaVez&&!e.pedido)||(tipo==='pife'&&minhaVez&&e.etapa==='descartar');ui.mao.append(elementoCarta(c,pode?()=>acaoCarta(e,i):null));});
 if(e.fim){ui.nova.classList.remove('escondido');ui.nova.disabled=e.partidaEncerrada===true;if(e.partidaEncerrada)ui.nova.textContent='Partida encerrada';}
 if(timerBot)clearTimeout(timerBot);const atual=js[e.atual];if(atual?.tipo==='bot'&&!e.fim)timerBot=setTimeout(()=>jogarBot(e,js,e.atual),700);
}
async function acaoCarta(e,i){try{if(tipo==='truco')await Truco.acoesTruco(salaRef,jogadorId).jogar(i);else if(tipo==='pife')await Pife.acoesPife(salaRef,jogadorId).descartar(i);}catch(err){console.error(err);mostrarToast('Não foi possível executar a jogada.','warn');}}
async function jogarBot(e,js,id){if(e.atual!==id||e.fim)return;try{if(tipo==='blackjack'){const p=Blackjack.pontuacao(e.maos[id]||[]);if(p<17)await Blackjack.acoesBlackjack(salaRef,id).comprar();else await Blackjack.acoesBlackjack(salaRef,id).parar();return;}if(tipo==='truco'){const mao=e.maos[id]||[];if(!e.pedido&&Truco.proximoPedido(e.valor)&&Math.random()<.18)await Truco.acoesTruco(salaRef,id).pedir(Truco.proximoPedido(e.valor));else{let best=0;for(let i=1;i<mao.length;i++){if(Truco.forca(mao[i],e.vira)>Truco.forca(mao[best],e.vira))best=i;}await Truco.acoesTruco(salaRef,id).jogar(best);}return;}if(tipo==='pife'){if(e.etapa==='comprar'){if(Math.random()<.35&&e.descarte?.length)await Pife.acoesPife(salaRef,id).comprarDescarte();else await Pife.acoesPife(salaRef,id).comprar();}else{const mao=e.maos[id]||[];let idx=mao.length-1;const conta={};mao.forEach(c=>conta[c.valor]=(conta[c.valor]||0)+1);const singles=mao.map((c,i)=>({c,i})).filter(x=>conta[x.c.valor]===1);if(singles.length)idx=singles.sort((a,b)=>rank(b.c)-rank(a.c))[0].i;await Pife.acoesPife(salaRef,id).descartar(idx);}}}catch(err){console.error('BOT',err);}}
async function garantirEstado(sala){if(!sala.estado&&sala.dono===jogadorId){await runTransaction(salaRef,s=>{if(!s||s.estado||s.status!=='jogando')return s;const ids=Object.entries(s.jogadores||{}).sort(([,a],[,b])=>(a.ordem||0)-(b.ordem||0)).map(([id])=>id);s.estado=criarEstadoPorJogo(s.jogo,ids,s.variacao,Object.fromEntries(ids.map((id,i)=>[id,s.jogadores[id].equipe||((s.jogo==='truco'&&ids.length===4)?(i%2?'vermelho':'azul'):undefined)]).filter(([,v])=>v)));return s;});}}
onValue(salaRef,async snap=>{if(!snap.exists()){ui.msg.textContent='A sala foi encerrada.';return;}const sala=snap.val();salaAtual=sala;if(sala.status!=='jogando'){location.href=`sala.html?codigo=${codigo}`;return;}if(sala.estado?.tipo==='buraco'||sala.estado?.tipo==='poker'){await update(salaRef,{estado:null,jogo:null,status:'aguardando'});return;}await garantirEstado(sala);if(sala.estado)render(sala.estado,sala.jogadores||{});});
ui.comprar.onclick=()=>tipo==='blackjack'?Blackjack.acoesBlackjack(salaRef,jogadorId).comprar():Pife.acoesPife(salaRef,jogadorId).comprar();
ui.passar.onclick=()=>tipo==='blackjack'?Blackjack.acoesBlackjack(salaRef,jogadorId).parar():null;
ui.desc.onclick=()=>Pife.acoesPife(salaRef,jogadorId).comprarDescarte();
ui.truco.querySelectorAll('button').forEach(b=>b.onclick=()=>Truco.acoesTruco(salaRef,jogadorId).pedir(Number(b.dataset.pedido)));
ui.aceitar.onclick=()=>Truco.acoesTruco(salaRef,jogadorId).responder('aceitar');ui.aumentar.onclick=()=>Truco.acoesTruco(salaRef,jogadorId).responder('aumentar');ui.recusar.onclick=()=>Truco.acoesTruco(salaRef,jogadorId).responder('recusar');
ui.nova.onclick=async()=>{if(!salaAtual?.estado)return;const act=jogos[tipo]?.acoesTruco||jogos[tipo]?.acoesPife;try{if(tipo==='truco')await Truco.acoesTruco(salaRef,jogadorId).novaRodada();else if(tipo==='blackjack'){const ids=salaAtual.estado.ids;await runTransaction(salaRef,s=>{if(!s?.estado?.fim)return s;const ids2=s.estado.ids;const deck=__shuffle(__deck());const maos=Object.fromEntries(ids2.map(x=>[x,[deck.pop(),deck.pop()]]));s.estado={...s.estado,deck,maos,dealer:[deck.pop(),deck.pop()],atual:ids2[0],parou:Object.fromEntries(ids2.map(x=>[x,false])),resultados:null,fim:false,resultado:""};return s;});}else {const ids=salaAtual.estado.ids;const deck=__shuffle(__deck());const maos=Object.fromEntries(ids.map(x=>[x,Array.from({length:9},()=>deck.pop())]));await update(salaRef,{estado:{tipo:'pife',ids,deck,maos,descarte:[deck.pop()],atual:ids[0],etapa:'comprar',placar:salaAtual.estado.placar||Object.fromEntries(ids.map(x=>[x,0])),fim:false,resultado:""}});}}catch(err){console.error(err);}};
ui.trocar.onclick=()=>location.href=`sala.html?codigo=${codigo}`;ui.organizar.onclick=()=>{const ordem={A:14,2:2,3:3,4:4,5:5,6:6,7:7,8:8,9:9,10:10,J:11,Q:12,K:13};maoCache=[...maoCache].sort((a,b)=>(ordem[a.valor]||0)-(ordem[b.valor]||0)||a.naipe.localeCompare(b.naipe));ui.mao.innerHTML='';maoCache.forEach(c=>ui.mao.append(elementoCarta(c)));};
function __deck(){return ["♠","♥","♦","♣"].flatMap(n=>["A","2","3","4","5","6","7","8","9","10","J","Q","K"].map(v=>({id:v+n,valor:v,naipe:n})));}function __shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
$('btnSair').onclick=async()=>{await remove(meuRef);location.href='index.html';};
