import {embaralhar,proximoJogador,sortearJogador,executarTransacao,nomeDe} from "../jogo-base.js";
const ORDEM=["4","5","6","7","Q","J","K","A","2","3"],NAIPE={"♦":0,"♠":1,"♥":2,"♣":3};
const deckTruco=()=>["♠","♥","♦","♣"].flatMap(n=>ORDEM.map(v=>({id:v+n,valor:v,naipe:n})));
const manilha=v=>ORDEM[(ORDEM.indexOf(v.valor)+1)%ORDEM.length];
export const forca=(c,v)=>c.valor===manilha(v)?100+NAIPE[c.naipe]:ORDEM.indexOf(c.valor);
export const proximoPedido=v=>({1:3,3:6,6:9,9:12})[v]||null;
const dupla=(ids,id,eq={})=>eq[id]==="azul"?0:eq[id]==="vermelho"?1:(ids.length===4?ids.indexOf(id)%2:ids.indexOf(id));
function fechar(e,js,d,msg){e.pontos[d]=(e.pontos[d]||0)+e.valor;e.fim=true;const nomes=e.ids.filter(id=>dupla(e.ids,id,e.equipes)===d).map(id=>nomeDe(js,id)).join(" e ");e.resultado=`${msg} ${nomes} ganhou ${e.valor} ponto${e.valor>1?"s":""}.`;if(e.pontos[d]>=12){e.partidaEncerrada=true;e.resultado+=` ${nomes} venceu a partida!`;}}
export function criarEstado(ids,_v,equipes={}){const deck=embaralhar(deckTruco()),maos=Object.fromEntries(ids.map(id=>[id,[deck.pop(),deck.pop(),deck.pop()]]));return{tipo:"truco",ids,equipes,deck,vira:deck.pop(),maos,atual:sortearJogador(ids),jogadas:{},vazas:[],rodada:1,valor:1,pontos:[0,0],pedido:null,ultimoPedidoPor:null,fim:false,partidaEncerrada:false,resultado:""};}
export function acoesTruco(ref,id){return{pedir:v=>executarTransacao(ref,e=>{if(e.tipo!=="truco"||e.fim||e.atual!==id||e.pedido||e.ultimoPedidoPor===id||proximoPedido(e.valor)!==v)return;e.pedido={de:id,para:proximoJogador(e.ids,id),valor:v};e.ultimoPedidoPor=id;}),responder:r=>executarTransacao(ref,(e,js)=>{if(!e.pedido||e.pedido.para!==id||e.fim)return;const p=e.pedido,d=dupla(e.ids,p.de,e.equipes);if(r==="recusar"){fechar(e,js,1-d,`${nomeDe(js,id)} correu.`);return;}if(r==="aceitar"){e.valor=p.valor;e.pedido=null;e.atual=p.de;return;}const n=proximoPedido(p.valor);if(n){e.pedido={de:id,para:p.de,valor:n};e.ultimoPedidoPor=id;}}),jogar:i=>executarTransacao(ref,(e,js)=>{if(e.tipo!=="truco"||e.fim||e.pedido||e.atual!==id)return;const c=e.maos[id]?.[i];if(!c)return;e.maos[id].splice(i,1);e.jogadas[id]=c;if(Object.keys(e.jogadas).length===e.ids.length){const vals=Object.entries(e.jogadas),max=Math.max(...vals.map(([,x])=>forca(x,e.vira))),w=vals.filter(([,x])=>forca(x,e.vira)===max).map(([x])=>x);e.ultimoVencedor=w.length===1?w[0]:id;e.vazas.push(w.length===1?dupla(e.ids,w[0],e.equipes):null);e.rodada++;e.jogadas={};const a=e.vazas.filter(x=>x===0).length,b=e.vazas.filter(x=>x===1).length;if(a>=2||b>=2||e.rodada>3){if(a===b){e.fim=true;e.resultado="Mão empatada. Ninguém pontua.";}else fechar(e,js,a>b?0:1,"A mão terminou:");}else{e.atual=e.ultimoVencedor;e.ultimoPedidoPor=null;}}else e.atual=proximoJogador(e.ids,id);}),novaRodada:()=>executarTransacao(ref,e=>{if(e.tipo!=="truco"||!e.fim||e.partidaEncerrada)return;const deck=embaralhar(deckTruco());e.deck=deck;e.vira=deck.pop();e.maos=Object.fromEntries(e.ids.map(pid=>[pid,[e.deck.pop(),e.deck.pop(),e.deck.pop()]]));e.jogadas={};e.vazas=[];e.rodada=1;e.valor=1;e.pedido=null;e.ultimoPedidoPor=null;e.atual=sortearJogador(e.ids);e.fim=false;e.resultado="";})};}